name: CI
on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        lfs: true
    - name: Install WinLibs
      run: choco install winlibs -y --no-progress
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: win64_mingw81
    - name: Run CMake
      run: |
        set PATH=C:\ProgramData\chocolatey\lib\winlibs\tools\mingw64\bin;%PATH%
        cmake_EclipseMinGW.bat 4 _Gcc
      working-directory: _Build
      shell: cmd
    - name: Build
      run: _build.bat
      working-directory: _Build/_Gcc
      shell: cmd
    - name: Copy Qt dependency DLLs
      run: |
        $bin = Resolve-Path "${env:Qt5_DIR}\..\..\..\bin"
        $dest = "_Build\_Gcc\_bin"

        Copy-Item "${bin}\libwinpthread-1.dll" -Destination $dest
        Copy-Item "${bin}\libstdc++-6.dll" -Destination $dest
        Copy-Item "${bin}\libgcc_s_seh-1.dll" -Destination $dest
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Kyty
        path: _Build/_Gcc/_bin
