name: CI
on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: win64_mingw81
    - name: Run CMake
      run: cmake_EclipseMinGW.bat 4 _Gcc
      working-directory: _Build
      shell: cmd
    - name: Build
      run: _build.bat
      working-directory: _Build/_Gcc
      shell: cmd
